# Generated by Django 5.0.6 on 2024-06-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_rename_user_article_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Article_User",
            new_name="Article_Writers",
        ),
    ]
