# Generated by Django 5.0.6 on 2024-06-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_rename_article_user_article_writers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article_Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(max_length=40, unique=True)),
                (
                    "sluq",
                    models.SlugField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Article_Writers",
        ),
    ]
