# Generated by Django 5.0.6 on 2024-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_article_writer_delete_article_writers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article_Writer",
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
