# Generated by Django 5.0.6 on 2024-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0010_alter_article_image_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(max_length=250),
        ),
    ]
